### ISSUE TITLE
Can it beep through the loudspeaker?

### ISSUE THREAD

**Issue by tarvos21** [liviu-/ding#10]
I have tried many ways to make my computer beep, but at last I found that there is no speaker on my motherboard, maybe because I assemble the compueter myself. And command like `beep` or any other command can not make any sound.
So if I want to beep through loudspeaker(this can work), how to do it? Thanks, maybe it will become too heavy for such a tool.
Anyway, it's cute. I like the idea, and once want to make one by myself.

**Comment by liviu-** [comment]
Hi, thanks for your interest!

If you can use any command that makes a sound, you may simply want to use `ding` as such:

```
$ ding in 1s --command your-command
```

There's a bit about this and how to make it more usable through a bash function in the [FAQ part](https://github.com/liviu-/ding#faq) of the README.md. Take a look and let me know if you run into any issues.
