### ISSUE TITLE
No beeping at all

### ISSUE THREAD

**Issue by faebser** [liviu-/ding#5]
I'm running your code on archlinux on a thinkpad t540p with

``` python
Python 3.5.2 (default, Jun 28 2016, 08:46:01) 
[GCC 6.1.1 20160602] on linux
```

There is no beeping at all.

**Comment by andars** [comment]
Try running `echo '\a'` and see if that beeps.

**Comment by liviu-** [comment]
If that doesn't work, you might've disabled the PC speakers: https://wiki.archlinux.org/index.php/Disable_PC_speaker_beep

**Comment by pacuna** [comment]
doesn't work for me in MacOS on iterm either

**Comment by liviu-** [comment]
@pacuna Does andars' suggestion work for you?

**Comment by pacuna** [comment]
@liviu- no, I'm not getting any beep with that command either

**Comment by liviu-** [comment]
@pacuna I am not very familiar with MacOS, nor do I have a system to test on right now, but I believe that they call this the "audible bell" and it may have been disabled for your terminal.

I would look around for ways to enable it (e.g. [1](https://superuser.com/questions/98868/how-do-i-disable-the-beep-in-osx-leopard-when-i-perform-an-invalid-action), [2](http://www.askbjoernhansen.com/2005/08/10/audible_bell_vo.html), [3](https://gunheeleo.blogspot.co.uk/2012/02/turn-off-iterm-beep-sound.html), [4](http://archive.robwilkerson.org/2009/07/27/disable-the-system-bell-in-iterm/))

**Comment by faebser** [comment]
@liviu- : i followed your advice and realised that the beep was disabled.
Now it works but only in the gnome terminal in [terminator](https://wiki.archlinux.org/index.php/Terminator) it does not beep. Maybe you can add that also the README.

**Comment by liviu-** [comment]
@faebser Glad to hear it worked! If it doesn't work for terminator, it may be that the beep is disabled for that terminal emulator specifically which may overwrite the system-wide configuration. I don't use terminator, but it might help to look around on how to enable it -- for example [here](http://crunchbang.org/forums/viewtopic.php?id=31178) they give some indications on how to manage it.

**Comment by im-n1** [comment]
@faebser You can set up custom beep command and it will work even in your headphones. Check out #8 for more info.

**Comment by liviu-** [comment]
Yeah, if you upgrade to 2.0.0 (`$ pip install --upgrade ding-ding` if you installed using `pip`), you can use `$ ding in 1s --command your-command-that-works` to use a custom command to beep when the countdown finished. More information about this was added in the README.md file.
