### ISSUE TITLE
Custom beep

### ISSUE THREAD

**Issue by im-n1** [liviu-/ding#8]
Hey there,

thanks for awesome tool!

I have (and as far as I know many people too) custom beep. Custom beep is simply alias for beep command which runs something like `paplay my-better-beep.wav`.
2 big advantages
- much more "listenable" beeps (http://www.soundjay.com/beep-sounds-1.html)
- works with headphones

The thing is it would be really nice to have ability to tell ding what to use as beep instead of just common "\a". Something like `ding -c beep in 3s` which will run beep command which is alias for paplay command above.

What do you think? Is this possible?

**Comment by liviu-** [comment]
Hiya! I'm happy you found the tool useful.

Thanks for the suggestion! Yes, I think it's a great idea, and I appreciate that some may be annoyed by the default sound. I'll add this today (or at least this week).

I was thinking of implementing it via an environment variable, such as:

``` sh
$ export DING_CUSTOM_COMMAND="beep"
$ ding in 3s # uses the command above instead of the default \a
```

Do you think this would be ok?

**Comment by im-n1** [comment]
For my case of usage it's ok. But maybe there can be both solutions. Some prefer system variables some aliases.

I guess it's up to you as head developer.

**Comment by liviu-** [comment]
I see, you're right -- I'll look into providing both options and let you know how it goes.

**Comment by liviu-** [comment]
Hey, I reimplemented the argument parser and added a `--command` / `-c` argument, so `$ ding in 3s -c beep` should work now (note that it requires the optional arguments at the end of the command due to how `argparse` uses subparsers). Haven't looked into hooking environment variables with `argparse` yet, but I'll check it out later.

I noticed the build fails on nightly right now with a segfault, and I can't investigate right now, but you can upgrade to the development version with `$ pip install --upgrade git+https://github.com/liviu-/ding` before I release 1.4.0 (or rather 2.0.0) which should be today or one of these days.

**Comment by im-n1** [comment]
Hey there,

amazing, thank you. I have tested and I realized that command run under ding how it's implemented doesn't work with my .bashrc. That means it can't see my aliases. But there is simple solution. See http://stackoverflow.com/questions/12060863/python-subprocess-call-a-bash-alias

You can set up own custom alias and run it with -c param. If it says something like `sh: 1: THAT_COMMAND: not found` it's wrong. Otherwise you won :)

Anyway when I call the new ding version like `ding in 3s -c "paplay --volume 15000 beep.wav"` it does work like a charm.

**Comment by liviu-** [comment]
Ohh, I see what you mean. Unfortunately, after having tried several ways to do get Python to invoke an alias, the only ones that could somewhat work were rather hacky approaches in the lines of `subprocess.call(['/bin/bash/', '--interactive', command])` which would still not work if the `alias` was loaded manually and not in the start-up script.

It's a bit unfortunate, but I think the best way forward is to have a bash script that calls it, or, like mikaylathompson suggested in #9, you could have something like this in your `.bashrc`:

``` bash
 function ding-c() { ding $@ -c "paplay --volume 15000 beep.wav"}
```

and just use `$ ding-c in 1s` when you want to use the custom sound.

Sorry for this! Please let me know if you have other suggestions or approaches to this.

**Comment by im-n1** [comment]
Well u r right. The function way works like a charm and it's the only way.

Thank you for the effort and cooperation. Cheers.
